### ISSUE TITLE
Corrección y adición de documentación en la WIKI del proyecto SARA

### ISSUE THREAD

**Issue by juusechec** [frameworksara/openSARA#16]
Se hicieron cambios en la documentación en el link.
https://github.com/JorgeUlises/sara/wiki
Se sugiere hacer un "merge" para cambiar la documentación.
### Se corrigió:

Errores de ortografía y malabras mal escritas.
### Se añadió:

Páginas:
"Instalación de SARA en Fedora 21"
"¿Cómo trabaja SARA?"
Nota: el repositorio de la WIKI contiene todas las imágenes agregadas a las nuevas entradas.

Gracias

**Comment by paulocoronado** [comment]
Por favor crear un pull request.

**Comment by juusechec** [comment]
En las wikis esto no es posible. https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github
Sin embargo se podrían hacer un merge localmente:
```sh
git clone https://github.com/frameworksara/openSARA.wiki.git
cd openSARA.wiki
git remote add fork https://github.com/juusechec/sara.wiki.git
git pull fork master
# resolver conflictos si los hay y hacer commit!
git push origin master
```

**Comment by frameworksara** [comment]
Ok. Se realizó el merge y se sincronizó la Wiki.
