### ISSUE TITLE
Correción Componente Notificador

### ISSUE THREAD

**Issue by jairolh** [frameworksara/openSARA#19]
En el archivo blocks/bannerUsuario/script/ajax.php, se invoca la variable $urlFinal  la cual no se define o se asigna valor con anterioridad, por tanto repercute en funcionamiento erroneo en el registro de eventos de la clase logger.class.php.

Para poder implementar el registro de logs sin inconvenientes en el framework Sara, es necesario modificar el archivo blocks/bannerUsuario/script/ajax.php.

Linea actual:

$cadena = $this->miConfigurador->fabricaConexiones->crypto->codificar_url ( $cadenaACodificar, $url );

Reemplazar para corregir por:

$urlFinal = $this->miConfigurador->fabricaConexiones->crypto->codificar_url ( $cadenaACodificar, $url );

**Comment by paulocoronado** [comment]
El notificador aún no hace parte del core de openSara. Se cierra la solicitud pero se recomienda tenerla en cuenta para instancias específicas de aplicaciones.
