### ISSUE TITLE
Sesiones de Usuario en frameworksara

### ISSUE THREAD

**Issue by violetasdev** [frameworksara/openSARA#33]
La versión actual de SARA posee una funcionalidad inicial para las sesiones de usuario. 

Una versión más trabajada del framework implementa las sesiones de usuario por roles, subsistemas y servicios, encontrándose estable. Es menester actualizar bloques del core como auth, log y manager para obtener una funcionalidad completa además de actualizar la estructura de la base de datos, lo anterior permite presentar el menú del aplicativo de acuerdo a los subsistemas y roles definidos, controlando el acceso. La generación de logs de eventos de forma más automatizada también está soportada en esta versión, pero sujeta a la forma de recuperación de sesiones del mismo.

Dado que SARA puede ser utilizado para cualquier tipo de desarrollo y no siempre será menester la utilización de tales clases, esta versión del framework está siendo analizada para ser un componente opcional a instalar dentro del mismo. Si se desea descargar los complementos necesarios, por ahora es posible hacerlo en proyectos como Tike, Arka, Polux, Titán y Argo. El script inicial de la base de datos será adjuntado. 

Con el código: 
Cambie las carpetas auth, manager, log y la clase ArmadorPagina.class.php del core/builder.
Agregue para GUI el bloque de menú con las funcionalidad lista.
Ejecute el script sql en el esquema de base de datos que soporta el framework. Cambie el prefijo del proyecto por el proyecto al cual se está realizando los ajustes.

Una ampliación de lo anterior será realizada en un documento con mayor detalle.

[ejemplo_menu_sesion.txt](https://github.com/frameworksara/sara/files/89144/ejemplo_menu_sesion.txt)

**Comment by paulocoronado** [comment]
Excelente!!!
