### ISSUE TITLE
Si la página dura más de cierto tiempo en cargarse Campo seguro da inconsistencias.

### ISSUE THREAD

**Issue by juusechec** [frameworksara/openSARA#41]
Al realizarse la carga de una página se da dos campos seguros diferentes, impidiendo la correcta carga de javascript al elemento.

En la misma página el elemento "docente" obtiene 2 diferentes valores de encripción para el ID:
Al principio del documento:
Enc: BAk36dD5EdhuNa-_X-kPUeRc5QxPgwLSX1i5ct7dlVw
Des: docente1472510419
Al final del documento:
Enc: drSCw92h3bB468j2lZZ_ur24hp3jL1eJTIYDXV8sINU
Des: docente1472508452

La solución temporal es quitar ese timestamp del código cuando el servidor es muy lento.

![screenshot from 2016-08-29 18-12-33](https://cloud.githubusercontent.com/assets/4140058/18070651/ed700618-6e14-11e6-9042-535bf183d631.png)
![screenshot from 2016-08-29 18-12-45](https://cloud.githubusercontent.com/assets/4140058/18070650/ed6f561e-6e14-11e6-8010-ea7040c8cbf7.png)

**Comment by JorgeUlises** [comment]
Las soluciones que se están ofreciendo por parte de desarrolladores udistrital:
$_REQUEST ['tiempo'] = intval(intval($_REQUEST ['tiempo'])/1000);
$_REQUEST ['tiempo'] = $_REQUEST ['tiempo']*1000;
$this->atributos ['tiempo'] = $_REQUEST ['tiempo'];

**Comment by paulocoronado** [comment]
Solución implementada.
